### ISSUE TITLE
Add GitHub ribbon

### ISSUE THREAD

**Issue by ayan-b** [ayan-b/GitHub-Activity-Checker#32]

**Comment by monsij** [comment]
✋

**Comment by monsij** [comment]
Can the search-bar be re positioned , as the ribbon won't be suitable elsewhere @ayan-b 
![ribbon](https://user-images.githubusercontent.com/23289387/54515848-52c9a180-4983-11e9-9926-ec3f89775941.JPG)

**Comment by ayan-b** [comment]
Just add a GitHub logo then?
