### ISSUE TITLE
Partial author name

### ISSUE THREAD

**Issue by monsij** [ayan-b/GitHub-Activity-Checker#34]
In the current activity list, only a part of the author's username is visible. Shouldn't it be complete?
Here is the screenshot: [Link](https://ibb.co/ThYRvg1)

**Comment by ayan-b** [comment]
Currently it works something similar to Google's Live Search, i.e, whenever some letters are pressed you will get live results for the same. This depends on internet connection speed, GitHub API requests' responses etc. So, sometimes the results are not displayed properly. In that case, search for the user name again. [Full Username Screenshot](https://screenshots.firefox.com/ph0N792zH0m8qG78/ghact.ga)

**Comment by ayan-b** [comment]
This can be improved by allowing the app to search only when <kbd>Enter</kbd> is pressed. One such attempt: https://github.com/ayan-b/GitHub-Activity-Checker/pull/22

**Comment by ayan-b** [comment]
Close this issue?
